config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  resources :questions
  resources :tags
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "questions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/text_formatter.rb
class TextFormatter
  def self.format_ruby_text(text,wrap,format=true)
    output = []
    new_text = text
    while new_text.length > wrap
      wrapped_text = new_text[0..wrap]
      if wrapped_text.include?("\n")
        scrapped = fetch_original_text(wrapped_text.split("\n"),"\n")
      elsif wrapped_text[-1] != " "
        scrapped = fetch_original_text(wrapped_text.split()," ")
      else
        scrapped = wrapped_text
      end
      output << scrapped.strip
      new_text.slice!(0,scrapped.length)
      new_text.strip!
    end
    output << new_text unless new_text.length.zero?
    return output.join("\n") unless format
    return output.map{ |line| arrange_line(line,wrap)}.join("\n")
  end

  def self.fetch_original_text(text,limiter)
    return text[0...-1].join(limiter)
  end

  def self.arrange_line(line,max_length)
    line_length = line.length
    remaining_length = max_length-line_length
    if remaining_length > 0
      space_count = compute_flag(line,nil)
      count = 0
      while true
        break if line.length >= max_length || compute_flag(line,count).nil?
        line.insert(compute_flag(line,count),"-")
        if count < space_count-1
          count += 1
        else
          count = 0
        end
      end
    end
    return line.gsub("-"," ")
  end

  def self.compute_flag(line,flag=0)
    indexes = line.enum_for(:scan,/ /).map { Regexp.last_match.begin(0) }
    return indexes.count if flag.nil?
    new_indexes = []
    while !indexes.empty?
      new_indexes << indexes.delete(indexes[0])
      new_indexes << indexes.delete(indexes[-1])
    end
    new_indexes.compact[flag]
  end
end

















# line.enum_for(:scan,/ /).map { Regexp.last_match.begin(0) }

# def self.format_text(text, wrap=50, indent=2)
#   result = []
#   work = text.dup
#   while work.length > wrap do
#     # binding.pry
#     if work =~ %r(^(.{0,#{wrap}})[ \n]) then
#       result << $1.rstrip
#       work.slice!(0, $&.length)
#     else
#       result << work.slice!(0, wrap)
#     end
#   end
#   result << work if work.length.nonzero?
#   puts result.join("\n").gsub(/^/, " " * indent)
#   result.join("\n").gsub(/^/, " " * indent)
# end



# def self.arrange_line(line,max_length)
#   line_length = line.length
#   remaining_length = max_length-line_length
#   if remaining_length > 0
#     while true
#       break if line.length >= 50
#       arr = compute_index(line)
#       arr_line = line.dup
#       arr.each_with_index do |index,key|
#         # binding.pry
#         break if line.length >= 50
#         line.insert(index,key.to_s) if line.length < 50
#       end
#     end
#   end
#   return line
# end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    # # binding.pry
    # @formatted_text = TextFormatter.format_ruby_text(File.read("input_text.txt"),50,false)
    # @formatted_ruby_text = TextFormatter.format_ruby_text(File.read("input_text.txt"),50)

  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)
    binding.pry
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :user_id, :tag_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation,:address)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password,:address)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_footer.html.erb
<footer class="colorgraph-footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3 text-center">
        <ul class="nav navbar-nav float-sm-right">
          <li class="nav-item">
            <a href="#"><i class="glyphicon glyphicon-home"></i> Home</a>
          </li>
          <li class="nav-item">
            <a href="#"><i class="glyphicon glyphicon-bullhorn"></i> Notice Board</a>
          </li>
          <li class="nav-item">
            <a href="#"><i class="glyphicon glyphicon-info-sign"></i> About</a>
          </li>
          <li class="nav-item">
            <a href="#"><i class="glyphicon glyphicon-envelope"></i> Contact Us</a>
          </li>
        </ul>
        <!--<small class="copyright text-muted small">Designed by IntlQ. Copyright &copy; 2016. All Rights Reserved.</small>-->
      </div>
    </div>
  </div><!--container ends-->
</footer>

app/views/layouts/_header.html.erb
<div class="collapse" id="exCollapsingNavbar">
  <div class="collapse-bg">
    <div class="card">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to "Question","#", class: "nav-link #{yield(:question_active)}"%>
        </li>
        <li class="list-group-item">
          <%= link_to "Answer","#", class: "nav-link #{yield(:answer_active)}"%>
        </li>
        <li class="list-group-item">
          <%= link_to "Account","#", class: "nav-link #{yield(:account_active)}"%>
        </li>
        <%= render partial: 'devise/menu/registration_items',locals: {class_name: "list-group-item"} %>
        <%= render partial: 'devise/menu/login_items',locals: {class_name: "list-group-item"} %>
      </ul>
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class="container">
    <a href="/" class="navbar-brand">
      Shri<span class="light">Shakti</span>
    </a>
    <button class="navbar-toggler hidden-sm-up float-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">&#9776;</button>
    <!--<form class="form-inline float-sm-right">-->
      <!--<div class="input-group input-group-sm">-->
        <!--<input type="text" class="form-control" placeholder="Search Query">-->
      <!--</div>-->
      <!--<button class="btn btn-outline-success btn-sm" type="submit">Go</button>-->
    <!--</form>-->
    <ul class="nav navbar-nav float-sm-right hidden-xs-down">
      <li class="nav-item">
        <%= link_to "Question","#", class: "nav-link #{yield(:question_active)}"%>
      </li>
      <li class="nav-item">
        <%= link_to "Answer","#", class: "nav-link #{yield(:answer_active)}"%>
      </li>
      <li class="nav-item">
        <%= link_to "Account","#", class: "nav-link #{yield(:account_active)}"%>
      </li>
      <%= render partial: 'devise/menu/registration_items',locals: {class_name: "nav-item"}  %>
      <%= render partial: 'devise/menu/login_items',locals: {class_name: "nav-item"}  %>
    </ul>
    <span>&nbsp;</span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %> | ShriShakti | </title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render "layouts/header"%>
<div class="container <%= controller_name %> <%= action_name %>">
  <%= yield %>
</div>
<%= render "layouts/footer" %>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_field :question %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :tag_id %>
    <%= f.text_field :tag_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>User</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question %></td>
        <td><%= question.user %></td>
        <td><%= question.tag %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

<pre><%=@formatted_text%></pre>

<h1> Ruby Formatted text </h1>
<pre><%=@formatted_ruby_text%></pre>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<%= provide(:page_title , @question.question)%>

<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>User:</strong>
  <%= @question.user %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @question.tag %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/tags/_form.html.erb
<%= form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>